/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.*;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author paco
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }

    public void setHangarView(HangarToUI h) {
        // cartelMaxElements.setText("Hangar espacial con
        // "+Integer.toString(h.getMaxElements())+" de capacidad");
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""),
                "Hangar espacial con " + Integer.toString(h.getMaxElements()) + " de capacidad"));

        panelWeapons.removeAll();
        panelShields.removeAll();

        for (WeaponToUI w : h.getWeapons()) {
            WeaponView wv = new WeaponView();
            wv.setWeaponView(w);
            panelWeapons.add(wv);
        }

        for (ShieldToUI s : h.getShieldBoosters()) {
            ShieldView sv = new ShieldView();
            sv.setShieldView(s);
            panelShields.add(sv);
        }

        repaint();
        revalidate();
    }

    ArrayList<Integer> getSelectedWeapons(){
        ArrayList<Integer> wea = new ArrayList();
        
        int i = 0; 
        for(Component w : panelWeapons.getComponents()){
            if(((WeaponView) w).isSelected()){
                wea.add(i);
            }
            i++;
        }
        return wea;
    }

    ArrayList<Integer> getSelectedShields(){
        ArrayList<Integer> wea = new ArrayList();
        
        int i = 0; 
        for(Component w : panelShields.getComponents()){
            if(((ShieldView) w).isSelected()){
                wea.add(i);
            }
            i++;
        }
        return wea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWeapons = new javax.swing.JPanel();
        panelShields = new javax.swing.JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShields, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
            .addComponent(panelWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelShields, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelShields;
    private javax.swing.JPanel panelWeapons;
    // End of variables declaration//GEN-END:variables
}
