/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.*;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author paco
 */
public class SpaceStationView extends javax.swing.JPanel {

    HangarView h;
    DamageView d;
    /**
     * Creates new form SpaceStationView
     */
    public SpaceStationView() {
        initComponents();
        d = new DamageView();
        h = new HangarView();
    }

    void setStationView(SpaceStationToUI sp) {
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""),
                "Estacion de " + sp.getName()));
        cartelMedallas.setText(Integer.toString(sp.getnMedals()));
        cartelAmmo.setText(Float.toString(sp.getAmmoPower()));
        cartelDefensa.setText(Float.toString(sp.getShieldPower()));
        cartelFuel.setText(Float.toString(sp.getFuelUnits()));

        panelDamage.removeAll();
        if (sp.getPendingDamage() != null) {
            d.setDamageView(sp.getPendingDamage());
            
            panelDamage.add(d);
        }

        panelHangar.removeAll();
        if (sp.getHangar() != null) {
            h.setHangarView(sp.getHangar());
            panelHangar.add(h);
            cartelNoHangar.setVisible(false);
        }else{
            cartelNoHangar.setVisible(true);
        }

        panelWeapons.removeAll();
        panelShields.removeAll();

        panelWeapons.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""),"Linea de fuego"));
        for (WeaponToUI w : sp.getWeapons()) {
            WeaponView vista = new WeaponView();
            vista.setWeaponView(w);
            panelWeapons.add(vista);
        }
        
        
       
        panelShields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""),
        "Linea de defensa"));
        for (ShieldToUI w : sp.getShieldBoosters()) {
            ShieldView vista2 = new ShieldView();
            vista2.setShieldView(w);
            panelShields.add(vista2);
        }


        repaint();
        revalidate();
    }

    ArrayList<Integer> getSelectedWeapons() {
        ArrayList<Integer> wea = new ArrayList();

        int i = 0;
        for (Component w : panelWeapons.getComponents()) {
            if (((WeaponView) w).isSelected()) {
                wea.add(i);
            }
            i++;
        }
        return wea;
    }

    HangarView getHangarView() {
        return h;
    }

    ArrayList<Integer> getSelectedShields() {
        ArrayList<Integer> wea = new ArrayList();

        int i = 0;
        for (Component w : panelShields.getComponents()) {
            if (((ShieldView) w).isSelected()) {
                wea.add(i);
            }
            i++;
        }
        return wea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelWeapons = new javax.swing.JPanel();
        panelShields = new javax.swing.JPanel();
        panelHangar = new javax.swing.JPanel();
        panelDamage = new javax.swing.JPanel();
        cartelMedallas = new javax.swing.JLabel();
        cartelFuel = new javax.swing.JLabel();
        cartelAmmo = new javax.swing.JLabel();
        cartelDefensa = new javax.swing.JLabel();
        cartelNoHangar = new javax.swing.JLabel();

        jLabel1.setText("Medallas:");

        jLabel2.setText("Combustible:");

        jLabel3.setText("Potencia de fuego:");

        jLabel4.setText("Potencia de defensa: ");

        cartelMedallas.setText("jLabel5");

        cartelFuel.setText("jLabel5");

        cartelAmmo.setText("jLabel5");

        cartelDefensa.setText("jLabel5");

        cartelNoHangar.setText("No tienes hangar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartelMedallas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartelFuel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartelAmmo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cartelDefensa)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cartelNoHangar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelShields, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cartelMedallas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cartelFuel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cartelAmmo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cartelDefensa)))
                    .addComponent(panelDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShields, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(cartelNoHangar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartelAmmo;
    private javax.swing.JLabel cartelDefensa;
    private javax.swing.JLabel cartelFuel;
    private javax.swing.JLabel cartelMedallas;
    private javax.swing.JLabel cartelNoHangar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelDamage;
    private javax.swing.JPanel panelHangar;
    private javax.swing.JPanel panelShields;
    private javax.swing.JPanel panelWeapons;
    // End of variables declaration//GEN-END:variables

}
